// w5_React/myapp/src/components/TodoList/TodoContent.js
import React from 'react';

import TodoItem from './TodoItem';

function TodoContent({datalist,removeItem,completeItem,selectItem}){
    // 函数组件的第一个参数props为父组件传入的属性组成的对象
    return (
        <div>
            <table>
                <thead>
                    <tr>
                        <th><input type="checkbox"/></th>
                        <th>#</th>
                        <th>事件</th>
                        <th>是否完成</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {datalist.map((item,idx)=>{
                        return <TodoItem 
                        key={item.id} 
                        item={item} 
                        idx={idx}
                        // removeItem={removeItem}
                        // completeItem={completeItem}
                        // selectItem={selectItem}
                        {...{removeItem,completeItem,selectItem}}
                        />
                    })}
                </tbody>
            </table>
        </div>
    )
}
export default TodoContent;

// w2_VueCli/myapp/src/components/TodoContent.vue
<template>
    <div>
       <table class="table table-striped">
            <thead>
                <tr>
                    <th><input type="checkbox" v-model="selectAll"/>全选</th>
                    <th>#</th>
                    <th>待办事项</th>
                    <th>是否完成</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                <TodoItem 
                v-for="(item,idx) in datalist" 
                :key="item.id"
                :item="item" 
                :idx="idx"
                @click.native="selectItem(idx)"
                ></TodoItem>
            </tbody>
        </table>
    </div>
</template>
<script>
import TodoItem from './TodoItem.vue';
import Bus from '../Bus'
export default {
    props:['datalist'],
    computed:{
        // 这里的属性为存储器属性
        selectAll:{
            get(){
                return this.datalist.every(item=>item.selected)
            },
            set(val){
                this.datalist.forEach(item=>{
                    item.selected = val
                })


            }
        }
    },
    components:{
        TodoItem
    },
    methods:{
        selectItem(idx){
            Bus.$emit('selectitem',idx)
        }
    }
}
</script>
<style>

</style>
